stages:
  - stage: windows_latest
    displayName: 'windows-latest'
    dependsOn: [  ]
    pool:
      vmImage: 'windows-latest'
    jobs:
      - job: Nuke
        displayName: 'Nuke'
        dependsOn: [  ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '$(System.DefaultWorkingDirectory)\artifacts\coverage\coverage.cobertura.xml'
              reportDirectory: '$(System.DefaultWorkingDirectory)\artifacts\coverage\coverage.cobertura.xml'
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'VSTest'
              testResultsFiles: '**/*.trx'
              searchFolder: '$(System.DefaultWorkingDirectory)\artifacts\tests'
              testRunTitle: 'Tests'
  - stage: ubuntu_latest
    displayName: 'ubuntu-latest'
    dependsOn: [  ]
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: Restore
        displayName: 'Restore'
        dependsOn: [  ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'